### ISSUE TITLE
Not able to open file

### ISSUE THREAD

**Issue by varnit15112** [several27/FakeNewsCorpus#1]
How to read the file? It's encoded somehow probably?

**Comment by several27** [comment]
Hey, @varnit15112 the file is compressed using zip. A simple `unzip news_cleaned_2018_02_13.csv.zip` should suffice 😊 And then it's just a plain text csv. If you have any further problems let me know. 

(Also, in next two days, I might publish a new version with a bit more data.)

**Comment by varnit15112** [comment]
When I download it, it gets saved as a '.csv'. I'm not able to read it using python3 and python2.7.

Error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 11: ordinal not in range(128)

Even when using utf-8:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 11: invalid start byte

**Comment by several27** [comment]
Ahh, I see the problem, really sorry about that, gonna push a fix right now. 

This line in the README:
```
aws s3 cp s3://researchably-fake-news-recognition/public_corpus/news_cleaned_2018_02_13.csv.zip news_corpus.csv
```
should have been:
```
aws s3 cp s3://researchably-fake-news-recognition/public_corpus/news_cleaned_2018_02_13.csv.zip news_corpus.csv.zip
```

Downloading a .csv.zip file to a .csv.zip file and not .csv.

A quick fix for you since you downloaded the data already would be just to rename the file to .csv.zip and then unpack it, so:
```
mv news_corpus.csv news_corpus.csv.zip
unzip news_corpus.csv.zip
```

Then you can e.g. use pandas to read the file like so:
```
import pandas as pd
news = pd.read_csv('news_cleaned_2018_02_13.csv', nrows=10000)
```

**Comment by varnit15112** [comment]
I have no clue why I didn't think of it earlier. Also do you have an accuracy over your dataset? I mean do you have a percentage score for which tags are you sure?

Thanks a ton!

**Comment by several27** [comment]
I don't have such data for now, but am planning to at least manually go through a small random sample of news. But from initial looking into the data, it seems like a majority of the articles are well classified. 

Feel free to provide any additional feedback and when you notice any articles wrongly classified just post an issue (with many examples at the same time, not to spam the GitHub issues too much). 

Thanks 😄
