### ISSUE TITLE
Getting the date of when each article was published

### ISSUE THREAD

**Issue by changxiaoxie** [several27/FakeNewsCorpus#11]
Hi @several27 , 

I am currently using your corpus for an NLP project and was wondering if you had the dates for when each article was published available. Otherwise I was wondering if you had the raw HTML for each article that I can download; I can retrieve these dates from the raw HTML. This is because a lot of the domains are dead and I can't look on the internet for these dates anymore.

Thanks,
Changxiao

**Comment by lbozarth** [comment]
Hey Changxiao,

do you have the current version of the dataset? I downloaded it before but now the link is broken. Is it possible for you to share that with me via email/dropbox/google drive?

**Comment by several27** [comment]
Unfortunately, the dataset doesn't contain dates. @lbozarth use this link: https://github.com/several27/FakeNewsCorpus/releases/tag/v1.0
