### ISSUE TITLE
Not able to get the zip file from wget command in Google colab

### ISSUE THREAD

**Issue by impawan** [several27/FakeNewsCorpus#12]
Hi,

When I am trying to download the file using wget command on google colab and I am getting below error:-

--2020-01-03 04:14:40--  https://storage.googleapis.com/researchably-fake-news-recognition/news_cleaned_2018_02_13.csv.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.97.128, 2404:6800:4008:c03::80
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.97.128|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-01-03 04:14:40 ERROR 403: Forbidden.

**Comment by lbozarth** [comment]
Hi impawan,
were you able to download the current version of the dataset? I downloaded it before but now the link is broken and I don't have the dataset anymore. Is it possible for you to share that with me via email/dropbox/google drive?

**Comment by impawan** [comment]
Hello Lbozarth,
I don't have the data with me. The other users who are following this repository might have the data.
Please let me know if you get any lead.

**Comment by natalyabikmetova** [comment]
Hello impawan and lbozarth, could you please let me know if you get this data? I am trying to get this too, but no luck yet..

**Comment by several27** [comment]
Hey all, 

Please use this: https://github.com/several27/FakeNewsCorpus/releases/tag/v1.0
