### ISSUE TITLE
Unable to extract the complete dataset

### ISSUE THREAD

**Issue by preksh1** [several27/FakeNewsCorpus#13]
Used this command to create a combined zip from the split parts in a directory:
_zip -F (name of last part of archive, which will end with .zip, not .z0X) --out (output name of compiled archive).zip_
and _unzip (archive name).zip_  to unpack it.Unpacking gives an error after an extraction of 2.8 GB of data.
Also used p7zip to unpack individual files or the combined file and get the error 
![Screenshot from 2020-02-11 18-49-11](https://user-images.githubusercontent.com/60337469/74240092-3d7a0600-4cff-11ea-9018-6b954fd24277.png)
 @several27 It'd be great if you could help me with this.

**Comment by Nurfen** [comment]
I am also having trouble unzipping the files. My error on mac is that the file format is not recognised.

Anyhow, thanks for your effort for making this dataset.

**Comment by bartoszkruba** [comment]
cat news.csv.z01 news.csv.z02 news.csv.z03 news.csv.z04 news.csv.z05 news.csv.z06 news.csv.z07 news.csv.z08 news.csv.z09 news.csv.zip > complete.zip

unzip complete.zip 

^^^
This works for me.

**Comment by Interstell** [comment]
It worked just fine for me:
`cat news.csv.{z01,z02,z03,z04,z05,z06,z07,z08,z09,zip} > temp.zip && unzip temp.zip`

**Comment by preksh1** [comment]
I found using the command or 7zip in windows works. I'm closing the issue.
