### ISSUE TITLE
NYTimes data?

### ISSUE THREAD

**Issue by ghdi6758** [several27/FakeNewsCorpus#3]
Dear Maciej,

Thanks a lot for making this amazing dataset available! :D I have one quick question and a comment. 
1. I found this dataset includes 1.5M NYTimes articles, can you elaborate little more how you collect them?
2. I'd love to use this dataset for research. But the lack of details on data collection procedure (e.g., when the collection started and ended, what is the time range of collected news articles) makes it really hard to use this data for academic purposes. If you can describe how you collected this data, it would be gratefully helpful! 

Thanks,
Jisun

**Comment by several27** [comment]
1. NYTimes articles were scraped directly from their website. The URLs that were scrapped were found through their developer API: https://developer.nytimes.com/
2. This project was a part of my dissertation, this report contains most of the information, but if it's missing any details feel free to ask: https://drive.google.com/file/d/1SPeBXjvbes9EmItDjR5PyRPkV54QsvPa/view?usp=sharing
