### ISSUE TITLE
Citing the dataset

### ISSUE THREAD

**Issue by hugoabonizio** [several27/FakeNewsCorpus#5]
Hi @several27!

I'm doing some research on fake news datasets for automatic detection and your corpus is the most complete I've found, it can be really useful for my study! But I don't know if you have a desirable way to cite your work of if it's published somewhere?
Do you have an email that I can contact you?

Thanks!

**Comment by several27** [comment]
Feel free to just cite the GitHub link and repo name. Thanks! 

I’ve sent you an email if you have further questions. Hope that helps.
