### ISSUE TITLE
wrong openmagazines.com content

### ISSUE THREAD

**Issue by simoons95** [several27/FakeNewsCorpus#7]
Hello!

Thank you for this huge dataset!
Currently working with it ("fake" and "reliable" labels only for now), I will probably find some problems in it, the majors of which I will post here :).

First one : 
contents of openmagazines.com articles are mainly the following:
"This website uses cookies to improve your experience. We'll assume you're ok with this, but you can opt-out if you wish. Accept"
for 1023 entries out of 1081. 
As a fast fix, automatically replacing this content with None or "" would be cleaner :).

**Comment by juewang1996** [comment]
Hi,

Could you tell how you download the data? I tried the two methods listed but both are failed.

**Comment by several27** [comment]
@simoons95 Thanks for the feedback! Do you happen to have a local copy of the dataset? If yes, could you share temporarily? I was moving some buckets over to a new cloud provider and might have corrupted some files in the process...
