### ISSUE TITLE
Cannot save data to database

### ISSUE THREAD

**Issue by KDawid** [several27/FakeNewsCorpus#9]
Hi,

I am trying to save the data into Cassandra database but it cannot interpret the CSV. After that I tried to check it with Excel and the pandas dataframe but both said that the file does not have a valid CSV format.

Could you help me to find the way how to store the data to Cassandra?

**Comment by several27** [comment]
Hey, 

Check out https://github.com/several27/FakeNewsCorpus/issues/1 to see how to read the file using pandas. 

I don't know much about data formats in Cassandra, but if it's anything like Elasticsearch, you should be able to open up the corpus in python, iterate over it in pandas, and upload each chunk to the whatever database you'd like without much work.
